# Introduction {.unnumbered}

This is my online notebook for COMP/STAT112 course taken at [Macalester College](https://www.macalester.edu/).  Please, use the side bar on the left for navigation.

Second day of class. We learned how to render and push the changes to github. Most people in class are very confused. 

9/10
Just finished Homework 1 and got it submitted to GitHub. Finally think I got it to work. I am now going to do the reading for class tomorrow and then fill out the survey on the central form. 

9/16:
Good reminder from this morning's class: Box plots are constructed from five numbers - the minimum, 25th percentile, median, 75th percentile, and maximum value of a quantitative variable.

9/18:
Just finished with Homework 2! Feeling pretty good about data visualization and creating plots. 

9/20:
Working on in-class activity but I got this error message: "Downloading GitHub repo ropensci/rnaturalearthhires@HEAD" I think I have finally got the naturalearth package to load and then we ran out of time. I got all the way to exercise 6. About to go fill out the central form for this. 

10/1:
Notes from Data Wrangling section:

The goals of Unit 2 are to explore how to:

Get data into the tidy shape / format we need for analysis. For example, we might want to:
keep only certain observations
define new variables
reformat or “clean” existing variables
combine various datasets
process “string” or text data
Numerically (not just visually) explore and summarize various characteristics of the variables in our dataset.
